server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092
    topic: "elastic-events"
    consumer:
      bootstrap-server: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: elastic-events-listener-group


  application:
    name: blog-service
  datasource:
    username: bloguser
    password: baturayacarturk
    url: jdbc:mysql://127.0.0.1:3306/blogdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: embedded
  flyway:
    user: bloguser
    password: baturayacarturk

secret:
  key: 47A52F686696CABA4A9824E6177DFFFF5161ASDFDS1D2DS

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

info:
  app:
    name: ${spring.application.name}
    description: "Blog Application"
    version: "1.0.0"

file:
  upload-dir: ./files

