

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: baturayacarturk
      MYSQL_ROOT_PASSWORD: verypowerfulpassword
    volumes:
      - ./blog/src/main/resources/scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -u$MYSQL_USER -p$MYSQL_PASSWORD" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - microservices-network

  postgres:
    image: postgres:13
    container_name: user_service_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: bacarturk
      POSTGRES_PASSWORD: bacarturk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U bacarturk -d userdb'" ]
      interval: 30s
      retries: 5
      timeout: 10s
    networks:
      - microservices-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=root
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:9200" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - microservices-network

volumes:
  mysql-data:
  postgres_data:
  elasticsearch-data:


